### ISSUE TITLE
2.3.3 support

### ISSUE THREAD

**Issue by kassner** [auroraextensions/googlecloudstorage#1]
Hi!

Which Magento versions this extension supports? I'm trying to run it on Magento 2.3.3 and I can manage it to same some images on my bucket, as expected, but the only ones that get there are under `catalog/product/cache`, but not the original ones like `catalog/product/m/y/my-product.png`.

In a quick investigation I can see that the class `Magento\Catalog\Model\Product\Gallery\CreateHandler`, that handles the image save/moving for Magento vanilla, never calls the GoogleCloudStorage extension to save it.

Thanks!

**Comment by nickolasburr** [comment]
Hi @kassner, this extension supports >=2.3.0. I will investigate this issue further and provide an update once I have more information.

**Comment by nickolasburr** [comment]
I'm able to reproduce this issue on Magento Open Source 2.3.3. I'm working on a fix and will release a patch update soon, hopefully within the next week. I will provide another update once I have released the patch update.

**Comment by nickolasburr** [comment]
Hi @kassner, this issue has been addressed in the latest release:

https://github.com/auroraextensions/googlecloudstorage/releases/tag/1.0.1

Thank you for taking the time to report this issue, I greatly appreciate it.
